
- name: install swarm cluster
  hosts: all
  become: yes
  roles:
  - docker
  - swarm
  - tooling

- name: install myapp
  hosts: all
  become: yes
  vars:
    nodeList: []
  roles:
  - myapp
  tags:
  - myapp