- hosts: localhost
  connection: local
  tasks:

  - name: list instances
    ec2_instance_info:
      aws_access_key: "{{ ec2_access_key }}"
      aws_secret_key: "{{ ec2_secret_key }}"
      region: "{{ region }}"
    register: __ec2_info

  - name: Instances ID
    debug:
      msg: "ID: {{ item.instance_id }} - State: {{ item.state.name }} - Public DNS: {{ item.public_dns_name }}"
    loop: "{{ __ec2_info.instances }}"

  - name: Upload public key to AWS
    ec2_key:
      name: "{{ key_name }}"
      key_material: "{{ lookup('file', '/home/oki/.ssh/id_rsa.pub') }}"
      region: "{{ region }}"
      aws_access_key: "{{ ec2_access_key }}"
      aws_secret_key: "{{ ec2_secret_key }}"
  
  - name: Create security group for wordpress
    ec2_group:
      name: "{{ sec_group_wordpress }}"
      description: "Sec group for {{ sec_group_wordpress }}"
      vpc_id: "{{ vpc_id }}"
      region: "{{ region }}"
      aws_access_key: "{{ ec2_access_key }}"
      aws_secret_key: "{{ ec2_secret_key }}"
      rules:
        - proto: tcp
          ports:
            - 22
          cidr_ip: 0.0.0.0/0
          rule_desc: allow all on ssh port
        - proto: tcp
          ports:
            - 80
          cidr_ip: 0.0.0.0/0
          rule_desc: allow http for allow
    register: __ec2_info_sec_group_wordpress
  
  - name: Create security group for mariadb
    ec2_group:
      name: "{{ sec_group_mariadb }}"
      description: "Sec group for {{ sec_group_mariadb }}"
      vpc_id: "{{ vpc_id }}"
      region: "{{ region }}"
      aws_access_key: "{{ ec2_access_key }}"
      aws_secret_key: "{{ ec2_secret_key }}"
      rules:
        - proto: tcp
          ports:
            - 22
          cidr_ip: 0.0.0.0/0
          rule_desc: allow all on ssh port
        - proto: tcp
          ports:
            - 3306
          cidr_ip: 172.31.0.0/16
          rule_desc: allow mariadb for allow
    register: __ec2_info_sec_group_mariadb

  - name: create instance
    ec2:
      aws_access_key: "{{ ec2_access_key }}"
      aws_secret_key: "{{  ec2_secret_key }}"
      key_name: "{{ key_name }}"
      id: "{{ id_wordpress }}-{{ ansible_date_time.date }}-1"
      group_id: "{{ __ec2_info_sec_group_wordpress.group_id }}"            
      image: "{{ image }}"
      instance_type: t2.micro
      region: "{{ region }}"
      wait: true
      instance_tags:
        Type: Wordpress
        Env: Production
      exact_count: 1
      count_tag:
        Type: Wordpress
    register: __wordpress_instances

  - name: create instance
    ec2:
      aws_access_key: "{{ ec2_access_key }}"
      aws_secret_key: "{{  ec2_secret_key }}"
      key_name: "{{ key_name }}"
      id: "{{ id_mariadb }}-{{ ansible_date_time.date }}-1"
      group_id: "{{ __ec2_info_sec_group_mariadb.group_id }}"
      image: "{{ image }}"
      instance_type: t2.micro
      region: "{{ region }}"
      wait: true
      instance_tags:
        Type: Mariadb
        Env: Production
      exact_count: 1
      count_tag:
        Type: Mariadb
    register: __mariadb_instances

  - name: add wordpress instances to inventory
    add_host:
      hostname: '{{ item.public_dns_name }}'
      ansible_host: '{{ item.public_dns_name }}'
      groups:
      - wordpress
    loop: "{{ __wordpress_instances.tagged_instances }}"

  - name: add mariadb instances to inventory
    add_host:
      hostname: '{{ item.public_dns_name }}'
      ansible_host: '{{ item.public_dns_name }}'
      mariadb_private_ip: '{{ item.private_dns_name }}'
      groups:
      - mariadb
    loop: "{{ __mariadb_instances.tagged_instances }}"

  - name: Wait for ssh to come up
    wait_for:
      host: '{{ item.public_dns_name }}'
      port: 22
      delay: 5
      timeout: 200
      state: started
    loop: "{{ __wordpress_instances.tagged_instances }}"

  - name: Wait for ssh to come up
    wait_for:
      host: '{{ item.public_dns_name }}'
      port: 22
      delay: 5
      timeout: 200
      state: started
    loop: "{{ __mariadb_instances.tagged_instances }}"

  - name: add volume to wordpresss instance
    ec2_vol:
      aws_access_key: "{{ ec2_access_key }}"
      aws_secret_key: "{{  ec2_secret_key }}"
      instance: "{{ item.id }}"
      region: "{{ region }}"
      volume_size: "10"
      volume_type: gp2
      device_name: /dev/xvdf
      delete_on_termination: yes
    loop: "{{ __wordpress_instances.tagged_instances }}"
    register: __ec2_volume_wordpress

  - name: add volume to mariadb instance
    ec2_vol:
      aws_access_key: "{{ ec2_access_key }}"
      aws_secret_key: "{{  ec2_secret_key }}"
      instance: "{{ item.id }}"
      region: "{{ region }}"
      volume_type: gp2
      volume_size: "20"
      device_name: /dev/xvdf
      delete_on_termination: yes
    loop: "{{ __mariadb_instances.tagged_instances }}"

- name: Install Mariadb
  remote_user: ubuntu
  hosts: mariadb
  become: yes
  tasks:

  - name: formatting the volume
    filesystem:
      dev: /dev/xvdf
      fstype: xfs

  - name: create mysql dir
    file:
      path: /var/lib/mysql
      state: directory
      owner: ubuntu
      group: ubuntu
      mode: 0775

  - name: mounting the filesystem
    mount:
      src: /dev/xvdf
      opts: noatime
      name: /var/lib/mysql
      fstype: xfs
      state: mounted

  - name: update cache
    apt:
      update_cache: yes
      cache_valid_time: 3600
      state: present

  - name: install mariadb
    apt:
      name: mariadb-server,python3-pymysql
      update_cache: yes
      state: present

  - name: start mariadb
    service:
      name: mariadb
      state: started

  - name: Create DB
    become_user: root
    mysql_db:
      name: "{{ mysql_db }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock

  - name: Create user
    become_user: root
    mysql_user:
      name: "{{ mysql_user }}"
      password: "{{ mysql_password }}"
      priv: "*.*:ALL"
      host: '%'
      login_unix_socket: /var/run/mysqld/mysqld.sock

  - name: change my.cnf
    lineinfile:
      dest: "/etc/mysql/my.cnf"
      line: "{{ item }}"
    with_items:
      - "[mysqld]"
      - "bind-address  = 0.0.0.0"
      - "# skip-networking"
    notify: restart_mariadb

  handlers:
  - name: restart_mariadb
    service:
      name: mariadb
      state: restarted

- name: Install Wordpress
  remote_user: ubuntu
  become: yes
  hosts: wordpress
  vars:
    wordpress_source: "https://wordpress.org/latest.tar.gz"
  tasks:

  - name: formatting the volume
    filesystem:
      dev: /dev/xvdf
      fstype: xfs

  - name: create wordpress dir
    file:
      path: /var/www/html
      state: directory
      owner: ubuntu
      group: ubuntu
      mode: 0775

  - name: mounting the filesystem
    mount:
      src: /dev/xvdf
      opts: noatime
      name: /var/www/html
      fstype: xfs
      state: mounted

  - name: install apache
    apt:
      update_cache: yes
      cache_valid_time: 3600
      name: apache2,php7.4-common,php7.4-mysql,libapache2-mod-php7.4,wget          
      state: present

  - name: start apache
    service:
      name: apache2
      state: started

  - name: check if wordpress exists"
    stat:
      path: "/var/www/html/wordpress/"
    register: __check_wordpress

  - name: drop file default index.html
    file:
      path: "/var/www/html/index.html"
      state: absent

  - name: download wordpress tar.gz
    unarchive:
      src: "{{ wordpress_source }}"
      dest: "/var/www/html/"
      remote_src: yes
    when: __check_wordpress.stat.exists == False

  - name: check if sample config exists
    stat:
      path: /var/www/html/wordpress/wp-config-sample.php
    register: __check_sample

  - name: rename wp-config-sample.php
    copy:
      src: /var/www/html/wordpress/wp-config-sample.php
      dest: /var/www/html/wordpress/wp-config.php
      remote_src: yes
    when: __check_sample.stat.exists == True and __check_wordpress.stat.exists == False

  - name: private ip for mariadb
    debug:
      msg: "{{ hostvars[groups['mariadb'][0]]['ansible_all_ipv4_addresses'] }}" 

  - name: modify wp-config.php
    lineinfile:
      dest: /var/www/html/wordpress/wp-config.php
      regexp: "{{ item.search }}"
      line: "{{ item.new }}"
      backrefs: yes
    with_items:
      - {'search': '^(.*)database_name_here(.*)$', 'new': '\1{{ mysql_db }}\2'}    
      - {'search': '^(.*)username_here(.*)$', 'new': '\1{{ mysql_user }}\2'}       
      - {'search': '^(.*)password_here(.*)$', 'new': '\1{{ mysql_password }}\2'} 
    when: __check_sample.stat.exists == True and __check_wordpress.stat.exists == False

  - name: modify wp-config.php - mariadb dns
    replace:
      path: /var/www/html/wordpress/wp-config.php
      regexp: 'localhost'
      replace: "{{ hostvars[groups['mariadb'][0]]['ansible_all_ipv4_addresses'][0] }}"
    when: __check_sample.stat.exists == True and __check_wordpress.stat.exists == False

  - name: change document root in apache2
    replace:
      path: /etc/apache2/sites-available/000-default.conf
      regexp: '/var/www/html$'
      replace: "/var/www/html/wordpress"
    notify: __reload_apache

  handlers:
  - name: __reload_apache
    service:
      name: apache2
      state: reloaded
  







