all:
  children:
    elastic:
      hosts:
        node1:
          ansible_host: 192.168.13.10
        node2:
          ansible_host: 192.168.13.11
    kibana:
      hosts:
        node1:
          ansible_host: 192.168.13.10

