
- name: install ansible pull
  hosts: localhost
  connection: local
  become: yes
  tasks:

  - name: create ssh dir
    file:
      path: /root/.ssh/
      mode: 0700
      owner: root
      group: root
      state: directory

  - name: push private key
    copy:
      content: "{{ pull_ssh_key_private }}"
      dest: /root/.ssh/id_rsa
      mode: 0600

  - name: install pull cron
    cron:
      name: ansible-pull
      cron_file: ansible-pull
      user: root
      job: "ansible-pull -U git@gitlab.com:xavki/my_ansible_pull.git --clean --purge --full --private-key /root/.ssh/id_rsa --accept-host-key 2>&1 >> /var/log/ansible-pull.log"

