- name: create a directory to store all files
  hosts: localhost
  connection: local
  tasks:
  - name: create dir
    file:
      path: collect_files/
      recurse: yes
  - name: run metabase
    docker_container:
      name: metabase
      image: metabase/metabase
      state: started
      detach: yes
      ports:
      - 3000:3000

- name: copy some files
  hosts: all
  become: yes
  roles:
  - collect
  - valo_web
  #- valo_mail
  - valo_databases