---
# handlers file for roles/elasticsearch_exporter

- name: reload_daemon_and_restart_elasticsearch_exporter
  systemd:
    name: elasticsearch_exporter
    state: restarted
    daemon_reload: yes
    enabled: yes
